//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PCLNative_TCSafety_014.Droid.WSTCSafety {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWSIncidentes", Namespace="http://tempuri.org/")]
    public partial class WSIncidentes : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListadoEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListadoUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListadoImpactadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListadoImpactoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListadoPotencialOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListadoAreaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListadoSubareaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListadoEstadoTipoIncidenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListadoTipoIncidenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListadoTipoLesionOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarIncidenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarIncidenteTipoIncidenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarInvolucradoOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarAnexoOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarAnexoIncidenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarAfectadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSIncidentes() {
            this.Url = "http://tcsafety.dyndns.org:45931/WSIncidentes.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getEmpresaCompletedEventHandler getEmpresaCompleted;
        
        /// <remarks/>
        public event getListadoEmpresaCompletedEventHandler getListadoEmpresaCompleted;
        
        /// <remarks/>
        public event getListadoUsuarioCompletedEventHandler getListadoUsuarioCompleted;
        
        /// <remarks/>
        public event getListadoImpactadoCompletedEventHandler getListadoImpactadoCompleted;
        
        /// <remarks/>
        public event getListadoImpactoCompletedEventHandler getListadoImpactoCompleted;
        
        /// <remarks/>
        public event getListadoPotencialCompletedEventHandler getListadoPotencialCompleted;
        
        /// <remarks/>
        public event getListadoAreaCompletedEventHandler getListadoAreaCompleted;
        
        /// <remarks/>
        public event getListadoSubareaCompletedEventHandler getListadoSubareaCompleted;
        
        /// <remarks/>
        public event getListadoEstadoTipoIncidenteCompletedEventHandler getListadoEstadoTipoIncidenteCompleted;
        
        /// <remarks/>
        public event getListadoTipoIncidenteCompletedEventHandler getListadoTipoIncidenteCompleted;
        
        /// <remarks/>
        public event getListadoTipoLesionCompletedEventHandler getListadoTipoLesionCompleted;
        
        /// <remarks/>
        public event guardarIncidenteCompletedEventHandler guardarIncidenteCompleted;
        
        /// <remarks/>
        public event guardarIncidenteTipoIncidenteCompletedEventHandler guardarIncidenteTipoIncidenteCompleted;
        
        /// <remarks/>
        public event guardarInvolucradoCompletedEventHandler guardarInvolucradoCompleted;
        
        /// <remarks/>
        public event guardarAnexoCompletedEventHandler guardarAnexoCompleted;
        
        /// <remarks/>
        public event guardarAnexoIncidenteCompletedEventHandler guardarAnexoIncidenteCompleted;
        
        /// <remarks/>
        public event guardarAfectadoCompletedEventHandler guardarAfectadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/getEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TCEmpresa getEmpresa() {
            object[] results = this.Invoke("getEmpresa", new object[0]);
            return ((TCEmpresa)(results[0]));
        }
        
        /// <remarks/>
        public void getEmpresaAsync() {
            this.getEmpresaAsync(null);
        }
        
        /// <remarks/>
        public void getEmpresaAsync(object userState) {
            if ((this.getEmpresaOperationCompleted == null)) {
                this.getEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmpresaOperationCompleted);
            }
            this.InvokeAsync("getEmpresa", new object[0], this.getEmpresaOperationCompleted, userState);
        }
        
        private void OngetEmpresaOperationCompleted(object arg) {
            if ((this.getEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEmpresaCompleted(this, new getEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/getListadoEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getListadoEmpresa() {
            object[] results = this.Invoke("getListadoEmpresa", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getListadoEmpresaAsync() {
            this.getListadoEmpresaAsync(null);
        }
        
        /// <remarks/>
        public void getListadoEmpresaAsync(object userState) {
            if ((this.getListadoEmpresaOperationCompleted == null)) {
                this.getListadoEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListadoEmpresaOperationCompleted);
            }
            this.InvokeAsync("getListadoEmpresa", new object[0], this.getListadoEmpresaOperationCompleted, userState);
        }
        
        private void OngetListadoEmpresaOperationCompleted(object arg) {
            if ((this.getListadoEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListadoEmpresaCompleted(this, new getListadoEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/getListadoUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getListadoUsuario(int id_empresa, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_empresaSpecified) {
            object[] results = this.Invoke("getListadoUsuario", new object[] {
                        id_empresa,
                        id_empresaSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getListadoUsuarioAsync(int id_empresa, bool id_empresaSpecified) {
            this.getListadoUsuarioAsync(id_empresa, id_empresaSpecified, null);
        }
        
        /// <remarks/>
        public void getListadoUsuarioAsync(int id_empresa, bool id_empresaSpecified, object userState) {
            if ((this.getListadoUsuarioOperationCompleted == null)) {
                this.getListadoUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListadoUsuarioOperationCompleted);
            }
            this.InvokeAsync("getListadoUsuario", new object[] {
                        id_empresa,
                        id_empresaSpecified}, this.getListadoUsuarioOperationCompleted, userState);
        }
        
        private void OngetListadoUsuarioOperationCompleted(object arg) {
            if ((this.getListadoUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListadoUsuarioCompleted(this, new getListadoUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/getListadoImpactado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getListadoImpactado() {
            object[] results = this.Invoke("getListadoImpactado", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getListadoImpactadoAsync() {
            this.getListadoImpactadoAsync(null);
        }
        
        /// <remarks/>
        public void getListadoImpactadoAsync(object userState) {
            if ((this.getListadoImpactadoOperationCompleted == null)) {
                this.getListadoImpactadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListadoImpactadoOperationCompleted);
            }
            this.InvokeAsync("getListadoImpactado", new object[0], this.getListadoImpactadoOperationCompleted, userState);
        }
        
        private void OngetListadoImpactadoOperationCompleted(object arg) {
            if ((this.getListadoImpactadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListadoImpactadoCompleted(this, new getListadoImpactadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/getListadoImpacto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getListadoImpacto(int id_impactado, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_impactadoSpecified) {
            object[] results = this.Invoke("getListadoImpacto", new object[] {
                        id_impactado,
                        id_impactadoSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getListadoImpactoAsync(int id_impactado, bool id_impactadoSpecified) {
            this.getListadoImpactoAsync(id_impactado, id_impactadoSpecified, null);
        }
        
        /// <remarks/>
        public void getListadoImpactoAsync(int id_impactado, bool id_impactadoSpecified, object userState) {
            if ((this.getListadoImpactoOperationCompleted == null)) {
                this.getListadoImpactoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListadoImpactoOperationCompleted);
            }
            this.InvokeAsync("getListadoImpacto", new object[] {
                        id_impactado,
                        id_impactadoSpecified}, this.getListadoImpactoOperationCompleted, userState);
        }
        
        private void OngetListadoImpactoOperationCompleted(object arg) {
            if ((this.getListadoImpactoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListadoImpactoCompleted(this, new getListadoImpactoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/getListadoPotencial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getListadoPotencial() {
            object[] results = this.Invoke("getListadoPotencial", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getListadoPotencialAsync() {
            this.getListadoPotencialAsync(null);
        }
        
        /// <remarks/>
        public void getListadoPotencialAsync(object userState) {
            if ((this.getListadoPotencialOperationCompleted == null)) {
                this.getListadoPotencialOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListadoPotencialOperationCompleted);
            }
            this.InvokeAsync("getListadoPotencial", new object[0], this.getListadoPotencialOperationCompleted, userState);
        }
        
        private void OngetListadoPotencialOperationCompleted(object arg) {
            if ((this.getListadoPotencialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListadoPotencialCompleted(this, new getListadoPotencialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/getListadoArea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getListadoArea() {
            object[] results = this.Invoke("getListadoArea", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getListadoAreaAsync() {
            this.getListadoAreaAsync(null);
        }
        
        /// <remarks/>
        public void getListadoAreaAsync(object userState) {
            if ((this.getListadoAreaOperationCompleted == null)) {
                this.getListadoAreaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListadoAreaOperationCompleted);
            }
            this.InvokeAsync("getListadoArea", new object[0], this.getListadoAreaOperationCompleted, userState);
        }
        
        private void OngetListadoAreaOperationCompleted(object arg) {
            if ((this.getListadoAreaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListadoAreaCompleted(this, new getListadoAreaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/getListadoSubarea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getListadoSubarea(int id_area, [System.Xml.Serialization.XmlIgnoreAttribute()] bool id_areaSpecified) {
            object[] results = this.Invoke("getListadoSubarea", new object[] {
                        id_area,
                        id_areaSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getListadoSubareaAsync(int id_area, bool id_areaSpecified) {
            this.getListadoSubareaAsync(id_area, id_areaSpecified, null);
        }
        
        /// <remarks/>
        public void getListadoSubareaAsync(int id_area, bool id_areaSpecified, object userState) {
            if ((this.getListadoSubareaOperationCompleted == null)) {
                this.getListadoSubareaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListadoSubareaOperationCompleted);
            }
            this.InvokeAsync("getListadoSubarea", new object[] {
                        id_area,
                        id_areaSpecified}, this.getListadoSubareaOperationCompleted, userState);
        }
        
        private void OngetListadoSubareaOperationCompleted(object arg) {
            if ((this.getListadoSubareaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListadoSubareaCompleted(this, new getListadoSubareaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/getListadoEstadoTipoIncidente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getListadoEstadoTipoIncidente() {
            object[] results = this.Invoke("getListadoEstadoTipoIncidente", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getListadoEstadoTipoIncidenteAsync() {
            this.getListadoEstadoTipoIncidenteAsync(null);
        }
        
        /// <remarks/>
        public void getListadoEstadoTipoIncidenteAsync(object userState) {
            if ((this.getListadoEstadoTipoIncidenteOperationCompleted == null)) {
                this.getListadoEstadoTipoIncidenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListadoEstadoTipoIncidenteOperationCompleted);
            }
            this.InvokeAsync("getListadoEstadoTipoIncidente", new object[0], this.getListadoEstadoTipoIncidenteOperationCompleted, userState);
        }
        
        private void OngetListadoEstadoTipoIncidenteOperationCompleted(object arg) {
            if ((this.getListadoEstadoTipoIncidenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListadoEstadoTipoIncidenteCompleted(this, new getListadoEstadoTipoIncidenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/getListadoTipoIncidente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getListadoTipoIncidente() {
            object[] results = this.Invoke("getListadoTipoIncidente", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getListadoTipoIncidenteAsync() {
            this.getListadoTipoIncidenteAsync(null);
        }
        
        /// <remarks/>
        public void getListadoTipoIncidenteAsync(object userState) {
            if ((this.getListadoTipoIncidenteOperationCompleted == null)) {
                this.getListadoTipoIncidenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListadoTipoIncidenteOperationCompleted);
            }
            this.InvokeAsync("getListadoTipoIncidente", new object[0], this.getListadoTipoIncidenteOperationCompleted, userState);
        }
        
        private void OngetListadoTipoIncidenteOperationCompleted(object arg) {
            if ((this.getListadoTipoIncidenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListadoTipoIncidenteCompleted(this, new getListadoTipoIncidenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/getListadoTipoLesion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getListadoTipoLesion() {
            object[] results = this.Invoke("getListadoTipoLesion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getListadoTipoLesionAsync() {
            this.getListadoTipoLesionAsync(null);
        }
        
        /// <remarks/>
        public void getListadoTipoLesionAsync(object userState) {
            if ((this.getListadoTipoLesionOperationCompleted == null)) {
                this.getListadoTipoLesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListadoTipoLesionOperationCompleted);
            }
            this.InvokeAsync("getListadoTipoLesion", new object[0], this.getListadoTipoLesionOperationCompleted, userState);
        }
        
        private void OngetListadoTipoLesionOperationCompleted(object arg) {
            if ((this.getListadoTipoLesionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListadoTipoLesionCompleted(this, new getListadoTipoLesionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/guardarIncidente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void guardarIncidente(
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string titulo, 
                    int idempresa, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool idempresaSpecified, 
                    System.DateTime fechaingreso, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool fechaingresoSpecified, 
                    System.DateTime fechaocurrencia, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool fechaocurrenciaSpecified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string relato, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string medidacontrol, 
                    int idimpacto, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool idimpactoSpecified, 
                    int idpotencial, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool idpotencialSpecified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lugar, 
                    int idarea, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool idareaSpecified, 
                    int idtipoanalisis, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool idtipoanalisisSpecified, 
                    int idestadotipoincidente, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool idestadotipoincidenteSpecified, 
                    int idsubarea, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool idsubareaSpecified, 
                    int idoperacion, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool idoperacionSpecified, 
                    int idoperacionunitaria, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool idoperacionunitariaSpecified, 
                    out int guardarIncidenteResult, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] out bool guardarIncidenteResultSpecified) {
            object[] results = this.Invoke("guardarIncidente", new object[] {
                        titulo,
                        idempresa,
                        idempresaSpecified,
                        fechaingreso,
                        fechaingresoSpecified,
                        fechaocurrencia,
                        fechaocurrenciaSpecified,
                        relato,
                        medidacontrol,
                        idimpacto,
                        idimpactoSpecified,
                        idpotencial,
                        idpotencialSpecified,
                        lugar,
                        idarea,
                        idareaSpecified,
                        idtipoanalisis,
                        idtipoanalisisSpecified,
                        idestadotipoincidente,
                        idestadotipoincidenteSpecified,
                        idsubarea,
                        idsubareaSpecified,
                        idoperacion,
                        idoperacionSpecified,
                        idoperacionunitaria,
                        idoperacionunitariaSpecified});
            guardarIncidenteResult = ((int)(results[0]));
            guardarIncidenteResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void guardarIncidenteAsync(
                    string titulo, 
                    int idempresa, 
                    bool idempresaSpecified, 
                    System.DateTime fechaingreso, 
                    bool fechaingresoSpecified, 
                    System.DateTime fechaocurrencia, 
                    bool fechaocurrenciaSpecified, 
                    string relato, 
                    string medidacontrol, 
                    int idimpacto, 
                    bool idimpactoSpecified, 
                    int idpotencial, 
                    bool idpotencialSpecified, 
                    string lugar, 
                    int idarea, 
                    bool idareaSpecified, 
                    int idtipoanalisis, 
                    bool idtipoanalisisSpecified, 
                    int idestadotipoincidente, 
                    bool idestadotipoincidenteSpecified, 
                    int idsubarea, 
                    bool idsubareaSpecified, 
                    int idoperacion, 
                    bool idoperacionSpecified, 
                    int idoperacionunitaria, 
                    bool idoperacionunitariaSpecified) {
            this.guardarIncidenteAsync(titulo, idempresa, idempresaSpecified, fechaingreso, fechaingresoSpecified, fechaocurrencia, fechaocurrenciaSpecified, relato, medidacontrol, idimpacto, idimpactoSpecified, idpotencial, idpotencialSpecified, lugar, idarea, idareaSpecified, idtipoanalisis, idtipoanalisisSpecified, idestadotipoincidente, idestadotipoincidenteSpecified, idsubarea, idsubareaSpecified, idoperacion, idoperacionSpecified, idoperacionunitaria, idoperacionunitariaSpecified, null);
        }
        
        /// <remarks/>
        public void guardarIncidenteAsync(
                    string titulo, 
                    int idempresa, 
                    bool idempresaSpecified, 
                    System.DateTime fechaingreso, 
                    bool fechaingresoSpecified, 
                    System.DateTime fechaocurrencia, 
                    bool fechaocurrenciaSpecified, 
                    string relato, 
                    string medidacontrol, 
                    int idimpacto, 
                    bool idimpactoSpecified, 
                    int idpotencial, 
                    bool idpotencialSpecified, 
                    string lugar, 
                    int idarea, 
                    bool idareaSpecified, 
                    int idtipoanalisis, 
                    bool idtipoanalisisSpecified, 
                    int idestadotipoincidente, 
                    bool idestadotipoincidenteSpecified, 
                    int idsubarea, 
                    bool idsubareaSpecified, 
                    int idoperacion, 
                    bool idoperacionSpecified, 
                    int idoperacionunitaria, 
                    bool idoperacionunitariaSpecified, 
                    object userState) {
            if ((this.guardarIncidenteOperationCompleted == null)) {
                this.guardarIncidenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarIncidenteOperationCompleted);
            }
            this.InvokeAsync("guardarIncidente", new object[] {
                        titulo,
                        idempresa,
                        idempresaSpecified,
                        fechaingreso,
                        fechaingresoSpecified,
                        fechaocurrencia,
                        fechaocurrenciaSpecified,
                        relato,
                        medidacontrol,
                        idimpacto,
                        idimpactoSpecified,
                        idpotencial,
                        idpotencialSpecified,
                        lugar,
                        idarea,
                        idareaSpecified,
                        idtipoanalisis,
                        idtipoanalisisSpecified,
                        idestadotipoincidente,
                        idestadotipoincidenteSpecified,
                        idsubarea,
                        idsubareaSpecified,
                        idoperacion,
                        idoperacionSpecified,
                        idoperacionunitaria,
                        idoperacionunitariaSpecified}, this.guardarIncidenteOperationCompleted, userState);
        }
        
        private void OnguardarIncidenteOperationCompleted(object arg) {
            if ((this.guardarIncidenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarIncidenteCompleted(this, new guardarIncidenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/guardarIncidenteTipoIncidente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void guardarIncidenteTipoIncidente(int idincidente, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idincidenteSpecified, int idtipoincidente, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idtipoincidenteSpecified) {
            this.Invoke("guardarIncidenteTipoIncidente", new object[] {
                        idincidente,
                        idincidenteSpecified,
                        idtipoincidente,
                        idtipoincidenteSpecified});
        }
        
        /// <remarks/>
        public void guardarIncidenteTipoIncidenteAsync(int idincidente, bool idincidenteSpecified, int idtipoincidente, bool idtipoincidenteSpecified) {
            this.guardarIncidenteTipoIncidenteAsync(idincidente, idincidenteSpecified, idtipoincidente, idtipoincidenteSpecified, null);
        }
        
        /// <remarks/>
        public void guardarIncidenteTipoIncidenteAsync(int idincidente, bool idincidenteSpecified, int idtipoincidente, bool idtipoincidenteSpecified, object userState) {
            if ((this.guardarIncidenteTipoIncidenteOperationCompleted == null)) {
                this.guardarIncidenteTipoIncidenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarIncidenteTipoIncidenteOperationCompleted);
            }
            this.InvokeAsync("guardarIncidenteTipoIncidente", new object[] {
                        idincidente,
                        idincidenteSpecified,
                        idtipoincidente,
                        idtipoincidenteSpecified}, this.guardarIncidenteTipoIncidenteOperationCompleted, userState);
        }
        
        private void OnguardarIncidenteTipoIncidenteOperationCompleted(object arg) {
            if ((this.guardarIncidenteTipoIncidenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarIncidenteTipoIncidenteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/guardarInvolucrado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void guardarInvolucrado(int idincidente, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idincidenteSpecified, int idusuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idusuarioSpecified, int idtipoinvolucrado, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idtipoinvolucradoSpecified, System.DateTime fechaasignacion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool fechaasignacionSpecified) {
            this.Invoke("guardarInvolucrado", new object[] {
                        idincidente,
                        idincidenteSpecified,
                        idusuario,
                        idusuarioSpecified,
                        idtipoinvolucrado,
                        idtipoinvolucradoSpecified,
                        fechaasignacion,
                        fechaasignacionSpecified});
        }
        
        /// <remarks/>
        public void guardarInvolucradoAsync(int idincidente, bool idincidenteSpecified, int idusuario, bool idusuarioSpecified, int idtipoinvolucrado, bool idtipoinvolucradoSpecified, System.DateTime fechaasignacion, bool fechaasignacionSpecified) {
            this.guardarInvolucradoAsync(idincidente, idincidenteSpecified, idusuario, idusuarioSpecified, idtipoinvolucrado, idtipoinvolucradoSpecified, fechaasignacion, fechaasignacionSpecified, null);
        }
        
        /// <remarks/>
        public void guardarInvolucradoAsync(int idincidente, bool idincidenteSpecified, int idusuario, bool idusuarioSpecified, int idtipoinvolucrado, bool idtipoinvolucradoSpecified, System.DateTime fechaasignacion, bool fechaasignacionSpecified, object userState) {
            if ((this.guardarInvolucradoOperationCompleted == null)) {
                this.guardarInvolucradoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarInvolucradoOperationCompleted);
            }
            this.InvokeAsync("guardarInvolucrado", new object[] {
                        idincidente,
                        idincidenteSpecified,
                        idusuario,
                        idusuarioSpecified,
                        idtipoinvolucrado,
                        idtipoinvolucradoSpecified,
                        fechaasignacion,
                        fechaasignacionSpecified}, this.guardarInvolucradoOperationCompleted, userState);
        }
        
        private void OnguardarInvolucradoOperationCompleted(object arg) {
            if ((this.guardarInvolucradoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarInvolucradoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/guardarAnexo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void guardarAnexo([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] byte[] imagetobytearray, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string extension, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nombre, System.DateTime fechacreacion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool fechacreacionSpecified, out int guardarAnexoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool guardarAnexoResultSpecified) {
            object[] results = this.Invoke("guardarAnexo", new object[] {
                        imagetobytearray,
                        extension,
                        nombre,
                        fechacreacion,
                        fechacreacionSpecified});
            guardarAnexoResult = ((int)(results[0]));
            guardarAnexoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void guardarAnexoAsync(byte[] imagetobytearray, string extension, string nombre, System.DateTime fechacreacion, bool fechacreacionSpecified) {
            this.guardarAnexoAsync(imagetobytearray, extension, nombre, fechacreacion, fechacreacionSpecified, null);
        }
        
        /// <remarks/>
        public void guardarAnexoAsync(byte[] imagetobytearray, string extension, string nombre, System.DateTime fechacreacion, bool fechacreacionSpecified, object userState) {
            if ((this.guardarAnexoOperationCompleted == null)) {
                this.guardarAnexoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarAnexoOperationCompleted);
            }
            this.InvokeAsync("guardarAnexo", new object[] {
                        imagetobytearray,
                        extension,
                        nombre,
                        fechacreacion,
                        fechacreacionSpecified}, this.guardarAnexoOperationCompleted, userState);
        }
        
        private void OnguardarAnexoOperationCompleted(object arg) {
            if ((this.guardarAnexoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarAnexoCompleted(this, new guardarAnexoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/guardarAnexoIncidente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void guardarAnexoIncidente(int idanexo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idanexoSpecified, int idincidente, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idincidenteSpecified, int idtipoanexoincidente, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idtipoanexoincidenteSpecified) {
            this.Invoke("guardarAnexoIncidente", new object[] {
                        idanexo,
                        idanexoSpecified,
                        idincidente,
                        idincidenteSpecified,
                        idtipoanexoincidente,
                        idtipoanexoincidenteSpecified});
        }
        
        /// <remarks/>
        public void guardarAnexoIncidenteAsync(int idanexo, bool idanexoSpecified, int idincidente, bool idincidenteSpecified, int idtipoanexoincidente, bool idtipoanexoincidenteSpecified) {
            this.guardarAnexoIncidenteAsync(idanexo, idanexoSpecified, idincidente, idincidenteSpecified, idtipoanexoincidente, idtipoanexoincidenteSpecified, null);
        }
        
        /// <remarks/>
        public void guardarAnexoIncidenteAsync(int idanexo, bool idanexoSpecified, int idincidente, bool idincidenteSpecified, int idtipoanexoincidente, bool idtipoanexoincidenteSpecified, object userState) {
            if ((this.guardarAnexoIncidenteOperationCompleted == null)) {
                this.guardarAnexoIncidenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarAnexoIncidenteOperationCompleted);
            }
            this.InvokeAsync("guardarAnexoIncidente", new object[] {
                        idanexo,
                        idanexoSpecified,
                        idincidente,
                        idincidenteSpecified,
                        idtipoanexoincidente,
                        idtipoanexoincidenteSpecified}, this.guardarAnexoIncidenteOperationCompleted, userState);
        }
        
        private void OnguardarAnexoIncidenteOperationCompleted(object arg) {
            if ((this.guardarAnexoIncidenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarAnexoIncidenteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWSIncidentes/guardarAfectado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void guardarAfectado(
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rut, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nombre, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string apellidos, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sexo, 
                    int edad, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool edadSpecified, 
                    int idempresa, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool idempresaSpecified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string area, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jefedirecto, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string experiencia, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string antiguedad, 
                    int idtipolesion, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool idtipolesionSpecified, 
                    int diasperdidos, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool diasperdidosSpecified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string consecuenciaobservacion, 
                    int idincidente, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool idincidenteSpecified) {
            this.Invoke("guardarAfectado", new object[] {
                        rut,
                        nombre,
                        apellidos,
                        sexo,
                        edad,
                        edadSpecified,
                        idempresa,
                        idempresaSpecified,
                        area,
                        jefedirecto,
                        experiencia,
                        antiguedad,
                        idtipolesion,
                        idtipolesionSpecified,
                        diasperdidos,
                        diasperdidosSpecified,
                        consecuenciaobservacion,
                        idincidente,
                        idincidenteSpecified});
        }
        
        /// <remarks/>
        public void guardarAfectadoAsync(
                    string rut, 
                    string nombre, 
                    string apellidos, 
                    string sexo, 
                    int edad, 
                    bool edadSpecified, 
                    int idempresa, 
                    bool idempresaSpecified, 
                    string area, 
                    string jefedirecto, 
                    string experiencia, 
                    string antiguedad, 
                    int idtipolesion, 
                    bool idtipolesionSpecified, 
                    int diasperdidos, 
                    bool diasperdidosSpecified, 
                    string consecuenciaobservacion, 
                    int idincidente, 
                    bool idincidenteSpecified) {
            this.guardarAfectadoAsync(rut, nombre, apellidos, sexo, edad, edadSpecified, idempresa, idempresaSpecified, area, jefedirecto, experiencia, antiguedad, idtipolesion, idtipolesionSpecified, diasperdidos, diasperdidosSpecified, consecuenciaobservacion, idincidente, idincidenteSpecified, null);
        }
        
        /// <remarks/>
        public void guardarAfectadoAsync(
                    string rut, 
                    string nombre, 
                    string apellidos, 
                    string sexo, 
                    int edad, 
                    bool edadSpecified, 
                    int idempresa, 
                    bool idempresaSpecified, 
                    string area, 
                    string jefedirecto, 
                    string experiencia, 
                    string antiguedad, 
                    int idtipolesion, 
                    bool idtipolesionSpecified, 
                    int diasperdidos, 
                    bool diasperdidosSpecified, 
                    string consecuenciaobservacion, 
                    int idincidente, 
                    bool idincidenteSpecified, 
                    object userState) {
            if ((this.guardarAfectadoOperationCompleted == null)) {
                this.guardarAfectadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarAfectadoOperationCompleted);
            }
            this.InvokeAsync("guardarAfectado", new object[] {
                        rut,
                        nombre,
                        apellidos,
                        sexo,
                        edad,
                        edadSpecified,
                        idempresa,
                        idempresaSpecified,
                        area,
                        jefedirecto,
                        experiencia,
                        antiguedad,
                        idtipolesion,
                        idtipolesionSpecified,
                        diasperdidos,
                        diasperdidosSpecified,
                        consecuenciaobservacion,
                        idincidente,
                        idincidenteSpecified}, this.guardarAfectadoOperationCompleted, userState);
        }
        
        private void OnguardarAfectadoOperationCompleted(object arg) {
            if ((this.guardarAfectadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarAfectadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WSmobile")]
    public partial class TCEmpresa {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        private string rUTField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RUT {
            get {
                return this.rUTField;
            }
            set {
                this.rUTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getEmpresaCompletedEventHandler(object sender, getEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TCEmpresa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TCEmpresa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getListadoEmpresaCompletedEventHandler(object sender, getListadoEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListadoEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListadoEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getListadoUsuarioCompletedEventHandler(object sender, getListadoUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListadoUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListadoUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getListadoImpactadoCompletedEventHandler(object sender, getListadoImpactadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListadoImpactadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListadoImpactadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getListadoImpactoCompletedEventHandler(object sender, getListadoImpactoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListadoImpactoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListadoImpactoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getListadoPotencialCompletedEventHandler(object sender, getListadoPotencialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListadoPotencialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListadoPotencialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getListadoAreaCompletedEventHandler(object sender, getListadoAreaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListadoAreaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListadoAreaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getListadoSubareaCompletedEventHandler(object sender, getListadoSubareaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListadoSubareaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListadoSubareaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getListadoEstadoTipoIncidenteCompletedEventHandler(object sender, getListadoEstadoTipoIncidenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListadoEstadoTipoIncidenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListadoEstadoTipoIncidenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getListadoTipoIncidenteCompletedEventHandler(object sender, getListadoTipoIncidenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListadoTipoIncidenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListadoTipoIncidenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getListadoTipoLesionCompletedEventHandler(object sender, getListadoTipoLesionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListadoTipoLesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListadoTipoLesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void guardarIncidenteCompletedEventHandler(object sender, guardarIncidenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarIncidenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarIncidenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int guardarIncidenteResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool guardarIncidenteResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void guardarIncidenteTipoIncidenteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void guardarInvolucradoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void guardarAnexoCompletedEventHandler(object sender, guardarAnexoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarAnexoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarAnexoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int guardarAnexoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool guardarAnexoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void guardarAnexoIncidenteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void guardarAfectadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591